### ISSUE TITLE
difference in output between sass-rails and sassc-rails

### ISSUE THREAD

**Issue by beauraF** [sass/sassc-rails#126]
Hello,

We tried to migrate from _sass-rails_ to _sassc-rails_ recently and we encountered some differences in output.

We have this code:

```scss
body:not(.configuration-template, .vpns-monitoring) {	
  div,	
  span,	
  p {	
    user-select: none;	
  }	
}
```

_sass-rails_ output:

```css
body:not(.configuration-template, .vpns-monitoring) div,
body:not(.configuration-template, .vpns-monitoring) span,
body:not(.configuration-template, .vpns-monitoring) p {
          user-select: none;
}
```

_sassc-rails_ output:

```css
body div,
body span,
body p {
          user-select: none;
}
```

The main problem comes from us because we use a CSS4 syntax.
**But** I find the behaviour of _sass-rails_ safer. It generates CSS that will just not be interpreted by the browser. When _sassc-rails_ generates CSS with a completely different behavior ; which actually broke us, several features.

What do u think about it ?
