### ISSUE TITLE
Inline source maps for vendored gems

### ISSUE THREAD

**Issue by rstacruz** [sass/sassc-rails#51]
I have vendored `chosen-rails` into `vendor/gems` like so:

```rb
gem 'chosen-rails', path: 'vendor/gems/chosen-rails'
```

Now I'm getting this error:

```css
          body:before {
            font-weight: bold;
            content: "\000a ExecJS::ProgramError: Error: \0022 \002f myproject\002f vendor\002f gems\002f chosen-rails\002f vendor\002f assets\002f stylesheets\002f chosen.css\0022  is not in the SourceMap.";
          }

          body:after {
            content: "\000a   SourceMapConsumer_sourceContentFor [as sourceContentFor] ((execjs):25357:15)";
          }
```
