### ISSUE TITLE
Assets not being recompiled after changes.

### ISSUE THREAD

**Issue by obromios** [sass/sassc-rails#55]
I am trying to convert from sass-rails to sassc-rails. I am using rails 4.2.2.

When I use sassc-rails, changes to my scss files are not being reflected in the view, even if I stop and restart the server (I have turned off spring). If I stop the server and do a rm -r tmp/cache/assets, the changes are reflected.

If I go back to sass-rails it works properly, though I have to do a rm -r tmp/cache/assets before I restart the server to have it working properly.

I have asked this question on stack overflow, http://stackoverflow.com/questions/34801411/sassc-rails-assets-changes-not-being-compiled/34815948#34815948, and there has been a suggestion, but no resolution of the problem.

**Comment by bolandrm** [comment]
I need more information to debug this.  I'm using a similar setup with no issues.

Could you please give me your gemfile / gemfile.lock and perhaps your application.scss?

**Comment by obromios** [comment]
Thank you.  Here is my Gemfile


```ruby
source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'gravatar_image_tag'
gem 'kaminari'
# Asssets
gem 'sprockets-rails', '>=2.1.4'
gem 'sassc-rails'
gem 'coffee-rails'
gem 'uglifier', '~> 2.7.2'
gem 'ransack'
gem 'bower-rails'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'autoprefixer-rails'
gem 'flexslider'
gem 'fitvidsjs_rails'
gem 'tinymce-rails'
# end Assets
# added in for backward compatability
gem 'protected_attributes'
# end backward compatability
gem 'jquery-rails', '~>3.1.3'
gem 'jquery-ui-rails'
gem 'execjs'
gem 'googlecharts', require: 'gchart'
gem 'pry'
gem 'pry-rails'
gem 'pg'
gem 'announcements', '~>0.2.0'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'simple_form', '~>3.1.0'
gem 'morrisjs-rails'
gem 'raphael-rails'
gem 'tilt'
gem 'puma'
# gem 'chris_lib', path: '../chris_lib'
gem 'chris_lib', git: 'https://github.com/obromios/chris_lib.git'
gem 'rails_12factor', group: [:production, :staging]
gem 'capybara', group: [:development, :test]
gem 'selenium-webdriver', group: [:development, :test]
gem 'capybara-webkit', group: [:development, :test]
gem 'rspec-rails', '~> 2.14.0.rc1', group: [:development, :test]
gem 'factory_girl_rails', group: [:development, :test]
# gem 'therubyracer',group: [:development,:test] #added for asset pipeline, takes up a lot of memory?
gem 'dotenv-rails', group: [:development, :test]
gem 'country_select', :git => 'https://github.com/stefanpenner/country_select'
gem 'heroku-api'
gem 'rack-timeout'
gem 'rack-attack'
gem 'test_changes', require: false
gem 'did_you_mean', group: [:development, :test]
group :production do
  ruby '2.1.6'
  gem 'newrelic_rpm'
  gem 'rack-rewrite' # for thegolfmentor.com redirect
end
group :development do
  gem 'annotate'
  gem 'faker'
  gem 'pry-nav'
  gem 'sextant'
  gem 'better_errors'
  gem 'binding_of_caller' # used by better_errors
  # gem 'rack-mini-profiler'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-livereload', require: false
  gem 'rack-livereload'
  gem 'rb-fsevent', :require => false
  gem 'guard-brakeman'
  gem 'stack_rescue'
  gem 'spring', '~>1.3.5'
  gem 'spring-commands-rspec'
  gem 'rubocop', '~>0.32.1', require: false
  gem 'redcarpet', '~> 3.2.3', require: false
  gem 'bundler-audit', require: false
end
group :test do
  gem 'webrat'
  gem 'launchy'
  gem 'simplecov', require: false
  gem 'database_cleaner'
end
```
and here is the `application.scss.css`
```scss
/*
*= require_self
*/
$Tempo-green: #6dbd63;
$site_width: 992px;
$grid-float-breakpoint: 992px;
$btn-default-bg: $Tempo-green;
$btn-default-color: #fff;
$btn-primary-bg: #6dbd63;
$field_bg: lighten($btn-default-bg, 30%);
$Mentor-green: #006400;
$Mentor-grey: #E6E6E6;
$Mentor-light-green: #AAE9AA;
@mixin standard-text{
	color:  #636363;
	font-family: 'Georgia, Helvetica', sans-serif;
	font-size: 14px;
	line-height: 16px;  
	}
@import "bootstrap-sprockets";
@import "bootstrap";
@import 'bootstrap_and_overrides';
@import "flexslider.css";
@import "admin.css.scss";
@import "accounts.css.scss";
@import "central.css.scss";
@import "common.css.scss";
@import "custom.css.scss";
@import "articles.css.scss";
@import "graph.css.scss";
@import "handicaps.css.scss";
@import "pages.css.scss";
@import "jquery.countdown.css";
@import "setups.css.scss";
@import "shared.css.scss";
@import "landings.css.scss";
@import "linkages.css.scss";
@import "professionals.css.scss";
@import "pro_users.css.scss";
@import "subscribers.css.scss";
@import "reviews.css.scss";
@import "mental_games.css.scss";
@import "students.css.scss";
@import "morris.css";
@import "users.css.scss";
@import "print.css.scss"


/* rest of file omitted */
```
